name: Shellspec Test for AWS SSM Parameters

on:
  push:
    branches:
      - gha-image-creation
  pull_request:
    branches:
      - gha-image-creation

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Create docker ecr
      run: echo "test"
