name: Devops-nxt demo, shellcheck demo with gha
on:
  push:
    branches:
      - shell-check-gha
jobs:
   shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Check shellcheck version 
        run: shellcheck -V

      -name: Check dir
       run: pwd 
