name: Shellspec Test for AWS SSM Parameters

on:
  push:
    branches:
      - shell-check-gha
  pull_request:
    branches:
      - shell-check-gha

jobs:
  shellspec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Install shellspec with git
      run: | 
        sudo mkdir -p /opt/shellspec
        sudo git clone https://github.com/shellspec/shellspec.git /opt/shellspec
        sudo ln -s /opt/shellspec/shellspec /usr/local/bin/shellspec
        shellspec -v

    - name: Export variable 
      run: | 
         source spec/env/dev.sh

    - name: Run Shellspec tests
      run: |
        shellspec spec/test_spec.sh
