name: Shellspec Test for AWS SSM Parameters

on:
  push:
    branches:
      - shell-check-gha
  pull_request:
    branches:
      - shell-check-gha

jobs:
  shellspec:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Install shellspec with git
      run: | 
        sudo mkdir -p /opt/shellspec
        sudo git clone https://github.com/shellspec/shellspec.git /opt/shellspec
        sudo ln -s /opt/shellspec/shellspec /usr/local/bin/shellspec
        shellspec -v

    # - name: Install Shellspec
    #   run: |
    #     # Download Shellspec
    #     curl -sL https://github.com/shellspec/shellspec/releases/download/0.28.1/shellspec-dist.tar.gz -o shellspec.tar.gz
    #     # Verify the file format
    #     file shellspec.tar.gz
    #     # Extract Shellspec
    #     tar xzf shellspec.tar.gz
    #     # Move Shellspec to /usr/local/bin
    #     sudo mv shellspec /usr/local/bin/
    #     # Verify installation
    #     shellspec --version
    #     # curl -sL https://github.com/shellspec/shellspec/releases/download/0.28.1/shellspec-dist.tar.gz | tar xz
    #     # sudo mv shellspec /usr/local/bin/
    #     # ls -l /usr/local/bin/shellspec
    #     # file /usr/local/bin/shellspec
    #     # chmod +x /usr/local/bin/shellspec
    #     # shellspec --version 

    - name: Run Shellspec tests
      run: |
        shellspec spec/test_spec.sh
